[tools]
go = ['latest']
github-cli = ['latest']

[env]
GHCR_USER="shige523"

[tasks.branch_cleanup]
description = "Delete mergerd branch"
run = "git checkout main;git fetch --prune;git branch --merged | egrep -v '\\*|main' |xargs git branch -d"

[tasks.ghcr_login]
description = "Delete mergerd branch"
run = "gh auth token | docker login ghrc.io -u ${GHCR_USER} --password-stdin"
