# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: local
  hooks:
    - id: actionlint
      name: actionlint via Docker
      description: Run actionlint in Docker container
      entry: docker run --rm -v $(pwd):/workdir -w /workdir rhysd/actionlint:latest
      language: system
      types: [yaml]
      files: ^\.github/workflows/.*\.ya?ml$
