name: Auto-merge-no-rule
on: pull_request
jobs:
  merge:
    #dependabotのリクエストのみ
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    #mergeに必要なパーミッション
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: dependabot/fetch-metadata@v2 #条件分岐でパッチバージョンかをチェック
      - if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        #patchバージョン変更時のみPR作成して、マージする
        # 他に、dependency-type（依存関係）,package-ecosystem（パッケージ種別）でも分岐可能
        name: auto-merge-no-rule
        run: |
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
