name: choice
on:
  workflow_dispatch:  #手動実行
    inputs:
      log_level:
        type: choice
        options:
          - info
          - warn
          - error
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.log_level }}"
