name: Concurrency
on:
  workflow_dispatch
concurrency: ${{ github.workflow }} #Concurrency グループへワークフロー名を指定。同じワークフローの多重起動を抑止
jobs:
  sleeps:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120
