name: Conditons2
on:
  workflow_dispatch:
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello1"
  must-run:
    if: ${{ github.actor == 'shige523' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello2"
