name: comment
on:
  pull_request:  #pr作成時に実行
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:          #github_tokenの権限を設定
      pull-requests: write #prへの書き込み許可
      cotntents: read     #ソースコードの読み込み許可
    steps:
      - uses: actions/chekout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}} #GitHub CLI用クレデンシャル
