name: manual
on:
  workflow_dispatch:  #手動実行
    inputs:
      greeting: #入力パラメータ名
        type: string
        default: Hello
        required: true
        description: 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
