name: masking-secrets
on: push
jobs:
  masking:
    runs-on: ubuntu-latest
    env:
      PASSWORD: SuperSecretValue
    steps:
      - run: echo "::addmask::${PASSWORD}"
      - run: echo "${PASSWORD}"
