name: Override environment variables
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      EXAMPLES: defined by workflow level
    steps:
      - run: echo "${EXAMPLES}"
      - env:
        EXAMPLES defined by step level # stepレベルで環境変数をoverrideする
        run : echo "${EXAMPLES}"
