name: use secrets
on:
  workflow_dispatch:  #手動実行
jobs:
  use-secrets:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }} # secretsの参照
    steps:
      - run: echo "${PASSWORD}" #outputはマスクされる
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" #outputはマスクされない
