name: github-output
run-name: run by @${{ github.actor }}
on:
  workflow_dispatch:  #手動実行
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: sourse #stepidを指定
        run: echo "result hello" >> "${GIHTUB_OUTPUT}" # GIHTUB_OUTPUTに出力
      - env:
          RESULT: ${{ steps.source.outputs.result }} # stepsコンテキストから参照
        run: echo "${RESULT}"
